name: ci

on: [push, pull_request]


jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x]
    steps:
      - name: SCM
        uses: actions/checkout@v3
      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install Dependencies and Build
        run: |
          yarn
          yarn test:cov
      - name: Upload coverage to Codecov
        if: matrix.node-version == '12.x'
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./reports/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
